# docker-compose.yml

services:
  backend:
    build: ./my-app-backend
    ports:
      - "3002:3002" # Map host port 3001 to container port 3001
    volumes:
      - ./my-app-backend:/app # Mount the backend code into the container
    environment:
      NODE_ENV: development # Example environment variable
      DB_HOST: db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password" # Replace with a strong password
      MYSQL_DATABASE: cars_db # Replace with your desired database name
      DB_HOST: localhost
    ports:
      - "3308:3306" # Map host port 3306 to container port 3306
    volumes:
      - db_data:/var/lib/mysql # Persist database data

volumes:
  db_data: